# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb3537e17d3afbae7a89613cbda4c4f726ae2d56b145524b08b1d3307b63e0a5e6f6f04dcd994aff56771834a4c116ca7f04466676d72ca05378a6f0bd6965f

test:
  secret_key_base: eacbb33480e68f38ecc68e995fd6631492d5d3cb45f5c1599035cd625664bd4635dc064cdd91a539b2d30cfe90693a8b99b08f580f9601a4a80757044a4b65df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
